- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-256
> Migrate from GitLab

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-250
> Add Helm linting

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-331
> Add SonarQube integration

- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-458
> PSD-458 JUnit separated out

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-430
> failed build reporting

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-471
> Add function to extract version from package.json

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-472
Shared library needs function to extract version from .csproj
> Add shared lib fn to get csproj version

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-473
> PSD-473 Add containter tagging using semver or pr

- README.md
- scripts/test
- src/uk/gov/defra/ffc/DefraUtils.groovy
- test/test-version-has-incremented.groovy
https://eaflood.atlassian.net/browse/PSD-474
Added new functions to support preventing merges from a PR where the version has not been incremented
> Validate version has incremented

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
Shared library needs function to create GitHub release tagged with version number if master build.
https://eaflood.atlassian.net/browse/PSD-475
> Shared library needs function to create GitHub release tagged with version number.

- src/uk/gov/defra/ffc/DefraUtils.groovy
Fix Helm command to correctly update version value using image tag.
https://eaflood.atlassian.net/browse/PSD-534
> Fix Helm not using correct image

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
- test/tests.groovy
https://eaflood.atlassian.net/browse/PSD-539
> Accomodate migration to non production

- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-543
> Fix Helm deployment version

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-512
We need functions to add and drop databases in an RDS instance
> Create and drop databases

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-537
The design rationale is documented in a confluence page. Create comments to link to this from the code
> Add links to documentation

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
Based on deployment pipelines for ffc-demo services.
> Add deployRemoteChart function

- README.md
- src/uk/gov/defra/ffc/DefraUtils.groovy
- test/tests.groovy
https://eaflood.atlassian.net/browse/PSD-566
Refactor provisionInfrastructure / destroyInfrastructure to work on
nonprod environment
> Move SQS Queue Provisioning to new AWS Env

- src/uk/gov/defra/ffc/DefraUtils.groovy
- test/tests.groovy
https://eaflood.atlassian.net/browse/PSD-584
Getting an error creating a new project as there is no previous version,
which the library considers invalid.
> Bug - First Version of a repository is considered invalid

- src/uk/gov/defra/ffc/DefraUtils.groovy
https://eaflood.atlassian.net/browse/PSD-620
> psd 620 helm 3 upgrade

- src/uk/gov/defra/ffc/Helm.groovy
- src/uk/gov/defra/ffc/Provision.groovy
- src/uk/gov/defra/ffc/Utils.groovy
Set schema in branch of 953 PR
> Update Helm deployment to use dynamic provisioned databases
